2022-11-27 12:29:00 INFO run.py:219 GNS3 server version 2.2.34
2022-11-27 12:29:00 INFO run.py:221 Copyright (c) 2007-2022 GNS3 Technologies Inc.
2022-11-27 12:29:00 INFO run.py:224 Config file /home/bazza/.config/GNS3/2.2/gns3_server.conf loaded
2022-11-27 12:29:00 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2022-11-27 12:29:00 INFO run.py:237 HTTP authentication is enabled with username 'admin'
2022-11-27 12:29:00 INFO run.py:243 Running with Python 3.10.8 and has PID 1251715
2022-11-27 12:29:00 INFO run.py:79 Current locale is en_AU.UTF-8
2022-11-27 12:29:00 INFO web_server.py:318 Starting server on 192.168.10.1:3078
2022-11-27 12:29:00 INFO __init__.py:63 Load controller configuration file /home/bazza/.config/GNS3/2.2/gns3_controller.conf
2022-11-27 12:29:00 INFO __init__.py:67 Controller is starting
2022-11-27 12:29:00 INFO compute.py:64 Create compute local
2022-11-27 12:29:00 INFO compute.py:364 Connecting to compute 'local'
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:29:00 INFO __init__.py:314 Start the GNS3 VM
2022-11-27 12:29:00 INFO compute.py:64 Create compute vm
2022-11-27 12:29:00 INFO notification_handler.py:50 New client has connected to compute WebSocket
2022-11-27 12:29:00 INFO compute.py:431 Connected to compute 'local' WebSocket 'http://192.168.10.1:3078/v2/compute/notifications/ws'
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/version HTTP/1.1" 200 228 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/version HTTP/1.1" 200 228 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO notification_handler.py:73 New client has connected to controller WebSocket
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/templates HTTP/1.1" 200 10834 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/computes HTTP/1.1" 200 1433 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/appliances?symbol_theme=Classic HTTP/1.1" 200 822486 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/projects HTTP/1.1" 200 184 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/projects HTTP/1.1" 200 184 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/symbols/%3A/symbols/router.svg/raw HTTP/1.1" 200 11038 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:00 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/symbols/%3A/symbols/vmware_guest.svg/raw HTTP/1.1" 200 20017 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/symbols/%3A/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 9274 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/symbols/%3A/symbols/vpcs_guest.svg/raw HTTP/1.1" 200 19496 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/symbols/%3A/symbols/cloud.svg/raw HTTP/1.1" 200 27983 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/symbols/%3A/symbols/docker_guest.svg/raw HTTP/1.1" 200 26605 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/symbols/%3A/symbols/hub.svg/raw HTTP/1.1" 200 7637 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:01 +0000] "GET /v2/symbols/%3A/symbols/frame_relay_switch.svg/raw HTTP/1.1" 200 10028 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:01 +0000] "GET /v2/symbols/%3A/symbols/atm_switch.svg/raw HTTP/1.1" 200 9960 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:01 INFO __init__.py:608 Searching for VMware VMs in inventory file "/home/bazza/.vmware/inventory.vmls"
2022-11-27 12:29:01 INFO __init__.py:426 Executing vmrun with command: /usr/bin/vmrun -T ws checkToolsState '/mythz/VMs/GNS3 VM/GNS3 VM.vmx'
2022-11-27 12:29:01 INFO __init__.py:426 Executing vmrun with command: /usr/bin/vmrun -T ws list
2022-11-27 12:29:01 INFO vmware_gns3_vm.py:153 Update GNS3 VM vCPUs and RAM settings
2022-11-27 12:29:01 INFO vmware_gns3_vm.py:87 GNS3 VM vCPU count set to 2 and RAM amount set to 2048
2022-11-27 12:29:01 INFO vmware_gns3_vm.py:156 Update GNS3 VM Hardware Virtualization setting
2022-11-27 12:29:01 INFO __init__.py:426 Executing vmrun with command: /usr/bin/vmrun -T ws start '/mythz/VMs/GNS3 VM/GNS3 VM.vmx' nogui
2022-11-27 12:29:03 INFO vmware_gns3_vm.py:164 GNS3 VM has been started
2022-11-27 12:29:03 INFO vmware_gns3_vm.py:169 Waiting for GNS3 VM IP
2022-11-27 12:29:04 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:04 +0000] "POST /v2/projects HTTP/1.1" 403 288 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:21 INFO vmware_gns3_vm.py:188 GNS3 VM IP address set to 192.168.10.129
2022-11-27 12:29:21 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 12:29:21 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 12:29:21 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:16 +0000] "POST /v2/projects/load HTTP/1.1" 409 308 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:29:26 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 12:29:26 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 12:29:31 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 12:29:31 INFO compute.py:431 Connected to compute 'vm' WebSocket 'http://192.168.10.129:80/v2/compute/notifications/ws'
2022-11-27 12:29:31 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:31 +0000] "GET /v2/compute/network/interfaces HTTP/1.1" 200 3648 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:35:47 INFO compute.py:457 Connection closed to compute 'local' WebSocket 'http://192.168.10.1:3078/v2/compute/notifications/ws'
2022-11-27 12:35:47 INFO compute.py:457 Connection closed to compute 'vm' WebSocket 'http://192.168.10.129:80/v2/compute/notifications/ws'
2022-11-27 12:35:48 INFO compute.py:364 Connecting to compute 'local'
2022-11-27 12:35:48 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 12:35:51 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2022-11-27 12:35:51 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:01:59:00 +0000] "GET /v2/compute/notifications/ws HTTP/1.1" 200 0 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:35:52 INFO web_log.py:206 192.168.1.100 [27/Nov/2022:02:05:52 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:35:52 INFO notification_handler.py:50 New client has connected to compute WebSocket
2022-11-27 12:35:52 INFO compute.py:431 Connected to compute 'local' WebSocket 'http://192.168.10.1:3078/v2/compute/notifications/ws'
2022-11-27 12:36:09 WARNING compute.py:367 Cannot connect to compute 'vm': Timeout error for GET call to http://192.168.10.129:80/v2/compute/capabilities after 20s
2022-11-27 12:36:09 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 12:36:09 INFO compute.py:431 Connected to compute 'vm' WebSocket 'http://192.168.10.129:80/v2/compute/notifications/ws'
2022-11-27 12:36:10 INFO project.py:78 Project 246cb1d4-5afc-4cb2-8c94-c8c4cdc16986 with path '/home/bazza/GNS3/projects/4CYNET1' created
2022-11-27 12:36:10 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:10 +0000] "POST /v2/compute/projects HTTP/1.1" 201 303 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:10 INFO docker_vm.py:1078 Docker container "Kali-Docker-1" [7d87689c-e72f-4b20-bc99-ef7210868024]: number of Ethernet adapters changed to 1
2022-11-27 12:36:10 INFO docker_vm.py:416 Docker container 'Kali-Docker-1' [7d87689c-e72f-4b20-bc99-ef7210868024] created
2022-11-27 12:36:10 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:10 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/docker/nodes HTTP/1.1" 201 938 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:10 INFO __init__.py:303 Creating new hypervisor 192.168.10.1:58613 with working directory /home/bazza/GNS3/projects/4CYNET1/project-files/dynamips
2022-11-27 12:36:10 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i1_log.txt', '-H', '192.168.10.1:58613']
2022-11-27 12:36:10 INFO hypervisor.py:129 Dynamips process logging to /home/bazza/GNS3/projects/4CYNET1/project-files/dynamips/dynamips_i1_stdout.txt
2022-11-27 12:36:10 INFO hypervisor.py:136 Dynamips process started PID=1300934
2022-11-27 12:36:10 INFO __init__.py:305 Hypervisor 192.168.10.1:58613 has successfully started
2022-11-27 12:36:10 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on 192.168.10.1:58613 after 0.1785 seconds
2022-11-27 12:36:10 INFO ethernet_switch.py:187 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209] has been created
2022-11-27 12:36:10 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:10 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes HTTP/1.1" 201 1562 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:10 INFO base_node.py:663 Starting new uBridge hypervisor 192.168.10.1:42101
2022-11-27 12:36:10 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', '192.168.10.1:42101']
2022-11-27 12:36:10 INFO hypervisor.py:171 logging to /home/bazza/GNS3/projects/4CYNET1/project-files/builtin/fba6ae55-2ecf-4d4c-a2d0-7f49ca51758e/ubridge.log
2022-11-27 12:36:10 INFO hypervisor.py:179 ubridge started PID=1300970
2022-11-27 12:36:10 INFO base_node.py:666 Hypervisor 192.168.10.1:42101 has successfully started
2022-11-27 12:36:11 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on 192.168.10.1:42101 after 0.1005 seconds
2022-11-27 12:36:11 INFO cloud.py:215 Cloud "Cloud1" [fba6ae55-2ecf-4d4c-a2d0-7f49ca51758e] has been created
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:10 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/cloud/nodes HTTP/1.1" 201 2652 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO vmware_vm.py:676 VMware VM 'Windows10x64-1-1' [7a37506d-5288-4fcb-b283-27a6eeb2e00c] has changed the number of Ethernet adapters to 1
2022-11-27 12:36:11 INFO vmware_vm.py:625 VMware VM "Windows10x64-1-1" [7a37506d-5288-4fcb-b283-27a6eeb2e00c] set the close action to "shutdown_signal"
2022-11-27 12:36:11 INFO vmware_vm.py:722 VMware VM 'Windows10x64-1-1' [7a37506d-5288-4fcb-b283-27a6eeb2e00c] is allowed to use any adapter
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes HTTP/1.1" 201 864 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO vmware_vm.py:676 VMware VM 'WindowsServer2016-1-1' [0d4a7e1c-bd16-442b-9b83-de00ae2026d2] has changed the number of Ethernet adapters to 1
2022-11-27 12:36:11 INFO vmware_vm.py:625 VMware VM "WindowsServer2016-1-1" [0d4a7e1c-bd16-442b-9b83-de00ae2026d2] set the close action to "shutdown_signal"
2022-11-27 12:36:11 INFO vmware_vm.py:722 VMware VM 'WindowsServer2016-1-1' [0d4a7e1c-bd16-442b-9b83-de00ae2026d2] is allowed to use any adapter
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes HTTP/1.1" 201 874 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO vmware_vm.py:676 VMware VM 'kali-linux-2022.3-vmware-amd64-1' [b364f2e1-c56c-41d4-8473-ba9c94b37cb3] has changed the number of Ethernet adapters to 1
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes HTTP/1.1" 201 856 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO vmware_vm.py:676 VMware VM 'blackarch-linux-2021.09.01-1' [0e77cc96-a185-4f39-97a2-31aa59fd1ab5] has changed the number of Ethernet adapters to 1
2022-11-27 12:36:11 INFO vmware_vm.py:625 VMware VM "blackarch-linux-2021.09.01-1" [0e77cc96-a185-4f39-97a2-31aa59fd1ab5] set the close action to "shutdown_signal"
2022-11-27 12:36:11 INFO vmware_vm.py:722 VMware VM 'blackarch-linux-2021.09.01-1' [0e77cc96-a185-4f39-97a2-31aa59fd1ab5] is allowed to use any adapter
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes HTTP/1.1" 201 840 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO ethernet_switch.py:275 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: NIO udp-5cafb761-e141-4665-be84-c20e4318591e bound to port 0
2022-11-27 12:36:11 INFO ethernet_switch.py:365 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: port 0 set as an access port in VLAN 1
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes/a0b1deaa-d0f6-4a6f-99bb-f501e0e42209/adapters/0/ports/0/nio HTTP/1.1" 201 395 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO ethernet_switch.py:275 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: NIO udp-695ad066-0c32-4155-9d47-daf82af54af3 bound to port 7
2022-11-27 12:36:11 INFO ethernet_switch.py:365 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: port 7 set as an access port in VLAN 1
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes/a0b1deaa-d0f6-4a6f-99bb-f501e0e42209/adapters/0/ports/7/nio HTTP/1.1" 201 393 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO docker_vm.py:980 Docker container 'Kali-Docker-1' [7d87689c-e72f-4b20-bc99-ef7210868024]: NIO UDP added to adapter 0
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/docker/nodes/7d87689c-e72f-4b20-bc99-ef7210868024/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO cloud.py:396 Cloud "Cloud1" [fba6ae55-2ecf-4d4c-a2d0-7f49ca51758e]: NIO NIO UDP bound to port 0
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/cloud/nodes/fba6ae55-2ecf-4d4c-a2d0-7f49ca51758e/adapters/0/ports/0/nio HTTP/1.1" 201 385 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO vmware_vm.py:763 VMware VM 'WindowsServer2016-1-1' [0d4a7e1c-bd16-442b-9b83-de00ae2026d2]: NIO UDP added to adapter 0
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes/0d4a7e1c-bd16-442b-9b83-de00ae2026d2/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:11 INFO ethernet_switch.py:275 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: NIO udp-0f68c847-3a6a-4a6f-88ed-354d043ee8e2 bound to port 1
2022-11-27 12:36:11 INFO ethernet_switch.py:365 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: port 1 set as an access port in VLAN 1
2022-11-27 12:36:11 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:11 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes/a0b1deaa-d0f6-4a6f-99bb-f501e0e42209/adapters/0/ports/1/nio HTTP/1.1" 201 393 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO vmware_vm.py:763 VMware VM 'Windows10x64-1-1' [7a37506d-5288-4fcb-b283-27a6eeb2e00c]: NIO UDP added to adapter 0
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes/7a37506d-5288-4fcb-b283-27a6eeb2e00c/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO ethernet_switch.py:275 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: NIO udp-9a2f8b7b-5f24-4425-9b0a-48ce39d70c37 bound to port 2
2022-11-27 12:36:12 INFO ethernet_switch.py:365 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: port 2 set as an access port in VLAN 1
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes/a0b1deaa-d0f6-4a6f-99bb-f501e0e42209/adapters/0/ports/2/nio HTTP/1.1" 201 393 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO vmware_vm.py:763 VMware VM 'kali-linux-2022.3-vmware-amd64-1' [b364f2e1-c56c-41d4-8473-ba9c94b37cb3]: NIO UDP added to adapter 0
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes/b364f2e1-c56c-41d4-8473-ba9c94b37cb3/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO ethernet_switch.py:275 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: NIO udp-c803751e-ec1d-4156-a18d-c9525f7a11f9 bound to port 3
2022-11-27 12:36:12 INFO ethernet_switch.py:365 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: port 3 set as an access port in VLAN 1
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes/a0b1deaa-d0f6-4a6f-99bb-f501e0e42209/adapters/0/ports/3/nio HTTP/1.1" 201 393 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO ethernet_switch.py:275 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: NIO udp-a8174139-b1dc-4b19-aa5f-40b3f3e8c743 bound to port 4
2022-11-27 12:36:12 INFO ethernet_switch.py:365 Ethernet switch "Switch1" [a0b1deaa-d0f6-4a6f-99bb-f501e0e42209]: port 4 set as an access port in VLAN 1
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes/a0b1deaa-d0f6-4a6f-99bb-f501e0e42209/adapters/0/ports/4/nio HTTP/1.1" 201 393 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO vmware_vm.py:763 VMware VM 'blackarch-linux-2021.09.01-1' [0e77cc96-a185-4f39-97a2-31aa59fd1ab5]: NIO UDP added to adapter 0
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes/0e77cc96-a185-4f39-97a2-31aa59fd1ab5/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:04 +0000] "POST /v2/projects/load HTTP/1.1" 201 731 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "GET /v2/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/nodes HTTP/1.1" 200 37372 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:36:12 INFO project_handler.py:272 New client has connected to the notification stream for project ID '246cb1d4-5afc-4cb2-8c94-c8c4cdc16986' (WebSocket method)
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "GET /v2/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/links HTTP/1.1" 200 10828 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "GET /v2/symbols/%3A/symbols/classic/multilayer_switch.svg/raw HTTP/1.1" 200 21518 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:36:12 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:06:12 +0000] "GET /v2/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/drawings HTTP/1.1" 200 206 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:39:28 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:09:27 +0000] "POST /v2/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/nodes/5895421c-109d-40a4-b374-d169edac23e7/start HTTP/1.1" 200 4383 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:39:29 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:09:29 +0000] "POST /v2/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/nodes/daa1abac-13c8-43a4-8a0e-92b2eb8d008d/start HTTP/1.1" 200 4383 "-" "GNS3 QT Client v2.2.34"
2022-11-27 12:39:32 INFO __init__.py:426 Executing vmrun with command: /usr/bin/vmrun -T ws list
2022-11-27 12:39:32 INFO base_node.py:663 Starting new uBridge hypervisor 192.168.10.1:35441
2022-11-27 12:39:32 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', '192.168.10.1:35441']
2022-11-27 12:39:32 INFO hypervisor.py:171 logging to /home/bazza/GNS3/projects/4CYNET1/project-files/vmware/0e77cc96-a185-4f39-97a2-31aa59fd1ab5/ubridge.log
2022-11-27 12:39:32 INFO hypervisor.py:179 ubridge started PID=1325744
2022-11-27 12:39:32 INFO base_node.py:666 Hypervisor 192.168.10.1:35441 has successfully started
2022-11-27 12:39:32 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on 192.168.10.1:35441 after 0.1007 seconds
2022-11-27 12:39:32 INFO __init__.py:426 Executing vmrun with command: /usr/bin/vmrun -T ws start /mythz/VMs/blackarch-linux-2021.09.01/blackarch-linux-2021.09.01.vmx
2022-11-27 12:39:36 INFO vmware_vm.py:483 VMware VM 'blackarch-linux-2021.09.01-1' [0e77cc96-a185-4f39-97a2-31aa59fd1ab5] started
2022-11-27 12:39:36 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:09:31 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/vmware/nodes/0e77cc96-a185-4f39-97a2-31aa59fd1ab5/start HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 12:39:36 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:02:09:31 +0000] "POST /v2/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/nodes/0e77cc96-a185-4f39-97a2-31aa59fd1ab5/start HTTP/1.1" 200 1937 "-" "GNS3 QT Client v2.2.34"
2022-11-27 20:48:54 INFO compute.py:457 Connection closed to compute 'vm' WebSocket 'http://192.168.10.129:80/v2/compute/notifications/ws'
2022-11-27 20:48:55 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:49:16 WARNING compute.py:367 Cannot connect to compute 'vm': Timeout error for GET call to http://192.168.10.129:80/v2/compute/capabilities after 20s
2022-11-27 20:49:21 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:49:23 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 20:49:28 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:49:48 WARNING compute.py:367 Cannot connect to compute 'vm': Timeout error for GET call to http://192.168.10.129:80/v2/compute/capabilities after 20s
2022-11-27 20:49:53 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:49:57 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 20:50:02 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:50:19 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 20:50:24 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:50:28 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 20:50:33 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:50:53 WARNING compute.py:367 Cannot connect to compute 'vm': Timeout error for GET call to http://192.168.10.129:80/v2/compute/capabilities after 20s
2022-11-27 20:50:58 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:51:02 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 20:51:07 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:51:27 WARNING compute.py:367 Cannot connect to compute 'vm': Timeout error for GET call to http://192.168.10.129:80/v2/compute/capabilities after 20s
2022-11-27 20:51:32 INFO compute.py:364 Connecting to compute 'vm'
2022-11-27 20:51:36 WARNING compute.py:367 Cannot connect to compute 'vm': Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 20:51:36 ERROR compute.py:373 Could not connect to compute 'vm' after multiple attempts: Cannot connect to host 192.168.10.129:80 ssl:default [Connect call failed ('192.168.10.129', 80)]
2022-11-27 20:51:36 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:10:21:36 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/docker/nodes/7d87689c-e72f-4b20-bc99-ef7210868024/stop HTTP/1.1" 204 188 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 20:51:36 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:10:21:36 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/ethernet_switch/nodes/a0b1deaa-d0f6-4a6f-99bb-f501e0e42209/stop HTTP/1.1" 204 197 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 20:51:36 INFO web_log.py:206 192.168.10.1 [27/Nov/2022:10:21:36 +0000] "POST /v2/compute/projects/246cb1d4-5afc-4cb2-8c94-c8c4cdc16986/cloud/nodes/fba6ae55-2ecf-4d4c-a2d0-7f49ca51758e/stop HTTP/1.1" 204 187 "-" "Python/3.10 aiohttp/3.8.3"
2022-11-27 20:51:36 INFO __init__.py:426 Executing vmrun with command: /usr/bin/vmrun -T ws list
